server:
  port: 8080

spring:
  application:
    name: mybatis-plus
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.bwin.mybatisplus.entity
  global-config:
    db-config:
      id-type: ID_WORKER_STR
      column-like: true

logging:
  file: ./logs/${spring.application.name}.log
  level:
    com.bwin.mybatisplus:
      mapper: DEBUG